### ISSUE TITLE
Exception when returning to a Select

### ISSUE THREAD

**Issue by ividyon** [FRACerqueira/PromptPlus#54]
With the following reproduction code:

```csharp
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using PPlus;

namespace ERMovesetTool;

public static class Reproduce
{
    internal enum Modes
    {
        [Display(Name = "String 1")]
        A,
        [Display(Name = "String 2")] B,

        [Display(Name = "String 3")]
        C,
    }
    public static void Do()
    {
        //Ensure ValueResult Culture for all controls
        PromptPlus.Config.DefaultCulture = new CultureInfo("en-us");

        PromptPlus.Banner("Banner").Run();

        while (true)
        {
            PromptPlus.DoubleDash("Double Dash String");
            PromptPlus.SingleDash("Single Dash String");

            var select = PromptPlus.Select<Modes>("Select operation")
                .Run();
            if (!select.IsAborted)
            {
                switch (select.Value)
                {
                    case Modes.A:
                        PromptPlus.DoubleDash("Double Dash String");

                        PromptPlus.WriteLine("String");
                        var anyKey = PromptPlus.KeyPress().Run();
                        break;
                    case Modes.B:
                        break;
                    case Modes.C:
                        break;
                }
            }

            PromptPlus.DoubleDash("Double Dash String");
            var repeat = PromptPlus.Confirm("Confirm?").Run();
            if (repeat.IsAborted || repeat.Value.IsNoResponseKey())
                break;
        }
    }
}
```

Upon building and publishing the code, and running the EXE, if I perform the following actions:

1. Select operation "String 1"
2. Press any key
3. Confirm with Y
4. Press Arrow Down to select another operation

I get the following exception:

![2023-08-11_02-39-10](https://github.com/FRACerqueira/PromptPlus/assets/1077140/abed462b-f8d4-4673-b2d3-9bf9cbb235cf)

This doesn't seem to happen if I run the app in the IntelliJ Rider "Run" terminal window, only if running the EXE (with Windows Terminal in Windows 11).

Running `PromptPlus.Clear()` at the start of the `while(true)` loop seems to avoid the problem.

**Comment by FRACerqueira** [comment]
Hi @ividyon!  please add to Banner's bottom command: 

PromptPlus.WriteLine($"IsTerminal: {PromptPlus.IsTerminal}");

Is the value true or false?

My machine is windows 10, there was probably a change in windows 11 in the ConsolePal class

**Comment by ividyon** [comment]
> PromptPlus.WriteLine($"IsTerminal: {PromptPlus.IsTerminal}");

This returns False.

**Comment by FRACerqueira** [comment]
in windows 10 it is true when using terminal, this is the reason for the problem.. I will investigate a way to solve it. thanks!

**Comment by FRACerqueira** [comment]
Hi @ividyon! Please update the Prompt Plus package with this preview version and try again. Notify me of the result
[PromptPlus.4.0.5-beta.zip](https://github.com/FRACerqueira/PromptPlus/files/12327791/PromptPlus.4.0.5-beta.zip)
