### ISSUE TITLE
Exception trying to filter Select prompt + some general questions

### ISSUE THREAD

**Issue by ividyon** [FRACerqueira/PromptPlus#59]
Hi,

I'm still continuing with my usage of PromptPlus, and continuing to stumble on new issues. I assume I am doing something wrong.

The code can be found [here](https://github.com/ividyon/WitchyBND/blob/format-redesign/WitchyBND/CliModes/ConfigMode.cs).

When I press any key, the Select seems to enter a "filter" mode. However, if I enter a string which does not exist in the options, I get the following exception:

![2023-09-13_19-11-57__WindowsTerminal](https://github.com/FRACerqueira/PromptPlus/assets/1077140/798fc5d8-35bf-41d7-a5e2-bc36d6f269f1)

1) How to resolve that error? Did I misconfigure something or is it a bug?
2) Can I disable the filter function? It's not needed in this case.
3) Can I disable other display functions, such as the "Choose an option:" prompt? The color highlighting of the selected option in the list is enough for me.

**Comment by FRACerqueira** [comment]
Hi,

1) How to resolve that error? Did I misconfigure something or is it a bug? 
A: Yes, fixed on commit https://github.com/FRACerqueira/PromptPlus/commit/f5bf26f844a08537dc1b122c59f36c204d466721 **(Roadmap confirmed for version 4.0.5)**

2) Can I disable the filter function? It's not needed in this case.  
A: No, but I created a new issue for it **(Roadmap planned for version 4.0.6)**

3) Can I disable other display functions, such as the "Choose an option:" prompt? 
A: No, but I created a new issue for it **(Roadmap planned for version 4.0.6)**

**Comment by FRACerqueira** [comment]
@ividyon , good news!

Updating:

How to resolve that error? Did I misconfigure something or is it a bug?
A: Yes, fixed on commit https://github.com/FRACerqueira/PromptPlus/commit/f5bf26f844a08537dc1b122c59f36c204d466721 (Roadmap confirmed for version 4.0.5)

Can I disable the filter function? It's not needed in this case.
A: No, but  fixed enhancement #60 (Roadmap confirmed for version 4.0.5)

Can I disable other display functions, such as the "Choose an option:" prompt?
A: No, but  fixed enhancement #61 (Roadmap confirmed for version 4.0.5)

Scheduled publication date to version 4.0.5 is 09/15/2023 or 09/16/2023

**Comment by FRACerqueira** [comment]
@ividyon 

I just published a **new release (v4.0.5).**

I created a new project in the 'Template/PromptPlusTemplate' folder.

This template, in addition to suggesting an implementation model, demonstrates the new properties that were created and some key configuration concepts (global and per control).

This example should resolve all items in your issue.

**Comment by ividyon** [comment]
Thank you for your swift work! I'll try it all out soon.
