### ISSUE TITLE
Escaping format characters (by default)

### ISSUE THREAD

**Issue by ividyon** [FRACerqueira/PromptPlus#65]
I'm having some trouble with how PromptPlus automatically formats characters in strings.

My program is processing files such as `C[c4201]_break.matbin`. When processing them, it prints them to the console:

```cs
                                PromptPlus.WriteLine($"Unpacking {parser.Name}: {fileName}...");
```
So, when `[]` is contained in the file name, PromptPlus stumbles and throws an exception due to applying internal formatting to this somehow, which I can't seem to find in the docs.

It would be quite nice if it was possible to disable this formatting; on a per-function-call basis, as well as as a global configuration that will automatically escape any formatting in strings entered in any WriteLine (and similar functions).

For starters, I'd like to know how to manually escape such characters, for now.

**Comment by FRACerqueira** [comment]
@ividyon , hi!

PromptPlus also has commands for coloring parts of text. To know the colored parts of the text, the characters '[' and ']' are used to delimit the color commands. (https://fracerqueira.github.io/PromptPlus/#colors)

I will investigate a way to have a global functionality to define these delimiters so as not to have an overhead for the end user.

To get around this problem you must use '[[' and ']]'

**Comment by FRACerqueira** [comment]
@ividyon , 'm working on this implementation.

The implementation so far looks like this:

```csharp
//local change AcceptMalformedColorToken
using (PromptPlus.IgnoreMalformedColorToken())
{
    PromptPlus.WriteLine("MalformedColorToken_AnyText[c4201]_Othertext");
    PromptPlus.WriteLine("ValidformedColorToken_Any[RED ON WHITE]Text[/]_[YELLOW]Othertext[/]");
}

//global change AcceptMalformedColorToken
PromptPlus.AcceptMalformedColorToken = true;
.
.
.
PromptPlus.WriteLine("MalformedColorToken_AnyText[c4201]_Othertext[/]");
PromptPlus.WriteLine("ValidformedColorToken_Any[RED ON WHITE]Text[/]_[YELLOW]Othertext[/]");
.
.
.
PromptPlus.AcceptMalformedColorToken = false;
```

**Comment by ividyon** [comment]
Looks like a great solution! I guess I'd call it something simpler like `EscapeColorTokens` or `EscapeStyleCharacters`, but yeah.

**Comment by FRACerqueira** [comment]
Good name for this feature!

**Comment by FRACerqueira** [comment]
Fixed scheduled for publication 4.0.6

**Comment by FRACerqueira** [comment]
@ividyon , See the changes, what do you think??


```csharp
            //standard 
            PromptPlus.DoubleDash($"PromptPlus IgnoreColorTokens = false - Default value and usage");
            PromptPlus.WriteLine("Valid[[]]formedColor_TokenAny[[RED ON WHITE]]Text[[/]]_[[YELLOW]]Othertext[[/]]");
            PromptPlus.WriteLine("ValidformedColor_TokenAny[RED ON WHITE]Text[/]_[YELLOW]Othertext[/]");

            PromptPlus.DoubleDash($"PromptPlus IgnoreColorTokens = true");
            //global change IgnoreColorTokens
            PromptPlus.IgnoreColorTokens = true;
            //show text with no color!
            PromptPlus.WriteLine("Valid[]formedColor_TokenAny[RED ON WHITE]Text[/]_[YELLOW]Othertext[/]");
            //create context to IgnoreColorTokens  = false
            using (PromptPlus.AcceptColorTokens())
            {
                PromptPlus.DoubleDash($"PromptPlus with context IgnoreColorTokens = false");
                //show text with color!
                PromptPlus.WriteLine("ValidformedColor_TokenAny[RED ON WHITE]Text[/]_[YELLOW]Othertext[/]");
            }
            PromptPlus.IgnoreColorTokens = false;

            //create context to IgnoreColorTokens  = true
            using (PromptPlus.EscapeColorTokens())
            {
                PromptPlus.DoubleDash($"PromptPlus with context IgnoreColorTokens = true");
                //show text with color
                PromptPlus.WriteLine("ValidformedColor_TokenAny[RED ON WHITE]Text[/]_[YELLOW]Othertext[/]");
            }
            //restore original value IgnoreColorTokens 

```
output:

![Captura de tela 2023-09-19 171806](https://github.com/FRACerqueira/PromptPlus/assets/45797410/8a78eb15-b86f-4806-ac58-a1631aa02ccc)

**Comment by ividyon** [comment]
Looks great!
