### ISSUE TITLE
Separators in Select?

### ISSUE THREAD

**Issue by ividyon** [FRACerqueira/PromptPlus#68]
Is it possible to have "separator" lines in Select elements?

![2023-09-18_20-10-32__WindowsTerminal](https://github.com/FRACerqueira/PromptPlus/assets/1077140/7db01a33-972b-4d73-9234-8416d590e234)

In this example, I'd like to have, for example, a dash line between the "Toggle" options and the others, which cannot be selected (the select would just hop over it to the next one).

```
  Toggle option A
> Toggle option B
  Toggle option C
  ---------------
  Menu option A
  Menu option B
  Menu option C
```

**Comment by FRACerqueira** [comment]
@ividyon ,
here is this feature for multiselect. I'll mark it as an improvement and it will be very similar (same commands). An example of what it would look like:

![selectnewfeature](https://github.com/FRACerqueira/PromptPlus/assets/45797410/5335b8e2-56d0-4aaa-80e2-318585829e3c)

**Comment by ividyon** [comment]
```
  Option 1
> Option 2
  Option 3
  ---------------
  Option 4
  Option 5
  Option 6
```
Just simple separating lines, no nesting

**Comment by FRACerqueira** [comment]
@ividyon done!, was maintaining a new item nesting option and adding the separation line option.  Note: When using the sort option in conjunction with separation line, the separation lines will be deleted

live Sample :

```csharp
           PromptPlus.Select<string>("Select")
                .AddItem("Seattle")
                .AddItem("New York")
                .AddSeparationline() //Default Separationline : SeparationLineType.SingleLine
                .AddItem("Tokyo")
                .AddItem("Singapore")
                .AddItem("Shanghai")
                .AddSeparationline(SeparationLineType.DoubleLine)
                .AddItem("London")
                .AddSeparationline(SeparationLineType.Char, '*')
                .AddItem("Other city")
                .Run();
```
![selectnewfeature](https://github.com/FRACerqueira/PromptPlus/assets/45797410/928c3654-ec97-4578-8817-0039e3218549)

**Comment by ividyon** [comment]
Awesome, thank you!

- I'd call it `Separator` since this is a fairly common term in programming for such things, rather than `Separationline` (it'd at least have to be `SeparationLine`).
- The separators/group titles seem to count towards the item count on the page (10 items when there's 8 + 2 separators).

**Comment by FRACerqueira** [comment]
@ividyon , No problem, change made to 'Separator' . I had already noticed that the item counter was taking into account separators and groupers, I just adjusted that too

```csharp

            PromptPlus.DoubleDash("Control:Select - basic usage with Separationline");
            PromptPlus.Select<string>("Select")
                 .AddItem("Seattle")
                 .AddItem("New York")
                 .Separator() //Default SeparatorLine : SeparatorLine.SingleLine
                 .AddItem("Tokyo")
                 .AddItem("Singapore")
                 .AddItem("Shanghai")
                 .Separator(SeparatorLine.DoubleLine)
                 .AddItem("London")
                 .Separator(SeparatorLine.Char, '*')
                 .AddItem("Other city")
                 .Run();
```
output :
![Captura de tela 2023-09-19 172255](https://github.com/FRACerqueira/PromptPlus/assets/45797410/cf2723e9-e82a-4fe9-a418-6500640a0029)

```csharp
            PromptPlus.DoubleDash("Control:Select - basic usage with group and AppendGroupOnDescription");
            PromptPlus.Select<string>("Which cities would you like to visit?")
                 .AddItemsGrouped("North America", new[] { "Seattle", "Boston", "New York" })
                 .AddItemsGrouped("Asia", new[] { "Tokyo", "Singapore", "Shanghai" })
                 .AddItem("South America (Any)")
                 .AddItem("Europe (Any)")
                 .AppendGroupOnDescription()
                 .Run();
```
output :
![Captura de tela 2023-09-19 180022](https://github.com/FRACerqueira/PromptPlus/assets/45797410/fe0f7b53-6e93-473a-98f9-a7997aad17bb)

**Comment by ividyon** [comment]
Perfect
