### ISSUE TITLE
No color on Bash

### ISSUE THREAD

**Issue by Anti-Apple4life** [FRACerqueira/PromptPlus#7]
I am using Arch Linux, and colors do not work.
![Screen Shot 2022-10-19 at 1 15 52 PM](https://user-images.githubusercontent.com/59315931/196759855-d630c4d2-41f0-447c-b02a-bce0520e011f.png)

**Comment by FRACerqueira** [comment]
try with new verseion 3.3.1 (Fixed bug - No color running linux when not set ConsoleDefaultColor)
